In [1]:
import pandas as pd 
import numpy as np 
import re

In [2]:
raw=pd.read_excel("project raw file.xlsx")
raw

       stNo             EmpName    surname
0    ST2462   Theodora Kansiime   Kansiime
1    ST1917          Oola Hilda       Oola
2    ST2208        Esebu Edward      Esebu
3    ST2735       Muwumba Norah    Muwumba
4    ST1787  Kababiito  Winfred  Kababiito
..      ...                 ...        ...
340  ST2545    Shallot Atukunda   Atukunda
341  ST2419         Ileka Grace      Ileka
342  ST2446       Emuria Joseph     Emuria
343  ST1853      Mugisa Michael     Mugisa
344  ST1942  Atuhairwe Peterson  Atuhairwe

[345 rows x 3 columns]

In [3]:
import sys
import os
import argparse

In [4]:

# 1. CONFIGURE THIS FOR YOUR DATA
raw = pd.read_excel("project raw file.xlsx")
raw["EmpName"] = raw["EmpName"].astype(str).str.strip().str.replace(r"\s+", " ", regex=True)
raw["surname"] = raw["surname"].astype(str).str.strip()

# 2. SCRIPT LOGIC

def standardize_one_name(full_name: str, surname_value: str):
    """
    Return a standardized name for one row.
    """
    if not isinstance(full_name, str) or not full_name.strip():
        return full_name

    if not isinstance(surname_value, str) or not surname_value.strip():
        return full_name

    words = full_name.split()
    surname_lower = surname_value.strip().lower()

    if surname_lower in [w.lower() for w in words]:
        others = [w for w in words if w.lower() != surname_lower]
        if others:
            return " ".join([w.title() for w in others + [surname_value]])
        return " ".join([w.title() for w in words])
    else:
        return " ".join([w.title() for w in words])


raw["EmpName"] = [
    standardize_one_name(row["EmpName"], row["surname"])
    for _, row in raw.iterrows()
]

# Keep only the updated name column for the output
result = raw[["stNo", "EmpName"]].copy()
result.head()

     stNo            EmpName
0  ST2462  Theodora Kansiime
1  ST1917         Hilda Oola
2  ST2208       Edward Esebu
3  ST2735      Norah Muwumba
4  ST1787  Winfred Kababiito

In [5]:
OUTPUT_FILE = "cleaned_project_file.xlsx"
raw.to_excel(OUTPUT_FILE, index=False, engine="openpyxl")
print("Saved:", OUTPUT_FILE)

Saved: cleaned_project_file.xlsx

In [6]:
new=pd.read_excel(OUTPUT_FILE)
new

       stNo             EmpName    surname
0    ST2462   Theodora Kansiime   Kansiime
1    ST1917          Hilda Oola       Oola
2    ST2208        Edward Esebu      Esebu
3    ST2735       Norah Muwumba    Muwumba
4    ST1787   Winfred Kababiito  Kababiito
..      ...                 ...        ...
340  ST2545    Shallot Atukunda   Atukunda
341  ST2419         Grace Ileka      Ileka
342  ST2446       Joseph Emuria     Emuria
343  ST1853      Michael Mugisa     Mugisa
344  ST1942  Peterson Atuhairwe  Atuhairwe

[345 rows x 3 columns]

In [ ]:
# Money cleaning function (for future files)
# def standardize_money(value):
#     if pd.isna(value):
#         return value

#     text = str(value).lower().replace(',', '').strip()
#     text = text.replace('ugx', '').strip()

#     multipliers = {
#         'k': 1_000,
#         'thousand': 1_000,
#         'm': 1_000_000,
#         'million': 1_000_000,
#         'b': 1_000_000_000,
#         'billion': 1_000_000_000,
#     }

#     match = re.match(r'(\d+(?:\.\d+)?)\s*([a-z]+)?', text)
#     if match:
#         num = float(match.group(1))
#         suffix = match.group(2)

#         if suffix in multipliers:
#             num *= multipliers[suffix]

#         return int(num)

#     return value

In [6]:
OUTPUT_FILE = "cleaned_project_file.xlsx"
# Replace all names for the same ID
raw["Standard_Name"] = raw["stNo"].map(id_lookup)

# Save output
raw.to_excel(OUTPUT_FILE, index=False, engine="openpyxl")

print(f"Saved: {OUTPUT_FILE}")

Saved: cleaned_project_file.xlsx